version: "3.4"
services:
    web:
        image: bblakemore312/group2_project4
        ports:
            - "5000:5000"
        networks:
            - webnet
    redis:
        image: redis
        networks:
            - webnet
networks:
    webnet:
